// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8yh9MnlbJwb_z_nEf8gh5RpFywx7IeNw',
    appId: '1:955271184769:web:4040ac95d39a5de02b2880',
    messagingSenderId: '955271184769',
    projectId: 'loginmvl',
    authDomain: 'loginmvl.firebaseapp.com',
    storageBucket: 'loginmvl.appspot.com',
    measurementId: 'G-F70PEWMWP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk7t3AdGmq5pYoWNS9vzCt4g-R5K0QFUU',
    appId: '1:955271184769:android:a558573a172f063d2b2880',
    messagingSenderId: '955271184769',
    projectId: 'loginmvl',
    storageBucket: 'loginmvl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC4B67weMNV6W1CL_PZ6lrdVpW8cWY6zM',
    appId: '1:955271184769:ios:9e6ae02176fe095f2b2880',
    messagingSenderId: '955271184769',
    projectId: 'loginmvl',
    storageBucket: 'loginmvl.appspot.com',
    androidClientId: '955271184769-47av8uodmqu9hsvlh5i7qh33uo63bjue.apps.googleusercontent.com',
    iosClientId: '955271184769-ubiqtme7sbnonp7h7rpkkcgf74j5bvmi.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC4B67weMNV6W1CL_PZ6lrdVpW8cWY6zM',
    appId: '1:955271184769:ios:d7f3bdf31391c84d2b2880',
    messagingSenderId: '955271184769',
    projectId: 'loginmvl',
    storageBucket: 'loginmvl.appspot.com',
    androidClientId: '955271184769-47av8uodmqu9hsvlh5i7qh33uo63bjue.apps.googleusercontent.com',
    iosClientId: '955271184769-iv6qr9d4uti71spciq8e1gtcqe6o0t2u.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginmobile.RunnerTests',
  );
}
